### ISSUE TITLE
Feedback on Type::Tiny::Manual::UsingWithClassTiny

### ISSUE THREAD

**Issue by tobyink** [cxw42/Class-Tiny-ConstrainedAccessor#10]
I've been rewriting a lot of the Type::Tiny documentation lately and was planning on including some documentation on using Class::Tiny::ConstrainedAccessor as a way to make Class::Tiny and Type::Tiny talk to each other.

Current draft:
https://metacpan.org/pod/release/TOBYINK/Type-Tiny-1.007_001/lib/Type/Tiny/Manual/UsingWithClassTiny.pod

Does it look okay to you? Anything else that you think needs to be mentioned? (I don't want to go into a huge amount of detail, because people can read the Class::Tiny::ConstrainedAccessor for more information if they need it.)

**Comment by cxw42** [comment]
Thank you for thinking of CTCA!  I will take a look.

**Comment by cxw42** [comment]
@tobyink I added a small amount of text while keeping in mind your desire not to go overboard :) .  I am closing this issue in favor of now-open https://github.com/tobyink/p5-type-tiny/pull/50 , where I look forward to any comments you may have.  Thanks!
