### ISSUE TITLE
Fails with recent vars::i

### ISSUE THREAD

**Issue by andk** [cxw42/Class-Tiny-ConstrainedAccessor#6]
Downgrading to CXW/vars-i-1.07.tar.gz does as a workaround.

Sample pass report with vars::i 1.07 http://www.cpantesters.org/cpan/report/6213b70a-7f27-11e9-ad21-6fb9494e4ebb

Report from same perl after upgrade: http://www.cpantesters.org/cpan/report/304f66ea-d69f-11e9-8956-bf4525a806fc

When I downgrade this same perl to CXW/vars-i-1.07.tar.gz, then the test passes again.

**Comment by cxw42** [comment]
Thanks!  I'll take a look.

**Comment by cxw42** [comment]
Looks like it's indeed triggered by cxw42/perl-vars-i#2 - see https://github.com/cxw42/Perl-vars-i/commit/caa9cf2c9242ba0fe9acc332228633c08fb09f70 , https://github.com/cxw42/Perl-vars-i/blob/caa9cf2c9242ba0fe9acc332228633c08fb09f70/lib/vars/i.pm#L22-L23 .  vars::I doesn't distinguish `$=>[]` (here) from `@=>[]`.  

I can add that to vars::I but first want to investigate why this module didn't die, and also didn't pass.  Single coderef should have worked, at least somewhat.

**Comment by cxw42** [comment]
@andk Would you please try https://github.com/cxw42/Perl-vars-i/releases/tag/v1.900000 and let me know how it goes?  It is a TRIAL release and works in my testing.  Thanks!

**Comment by andk** [comment]
>>>>> On Sun, 15 Sep 2019 19:29:49 -0700, Chris White <notifications@github.com> said:

  > @andk Would you please try
  > https://github.com/cxw42/Perl-vars-i/releases/tag/v1.900000 and let me
  > know how it goes? It is a TRIAL release and works in my testing.
  > Thanks!

Looks good (but you know, "Testing shows the presence, not the absence of
bugs". Dijkstra (1969)) :)

Thanks,
-- 
andreas
